version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis_container:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: redispassword
    ports:
      - 6379:6379
    volumes:
      - redis_data_container:/bitnami/redis/data
  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  mongodb_data_container:
  redis_data_container:
  postgresdata:
